<a href="https://colab.research.google.com/github/Thiago-Magnago/Thiago-Magnago/blob/main/Munic%C3%ADpios_IBGE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notebook para obtenção dos municípios brasileiros junto a API do IBGE

In [ ]:
import json
import requests

#url = 'https://servicodados.ibge.gov.br/api/v1/localidades/regioes/1|2|3|4|5/municipios'
url = 'https://servicodados.ibge.gov.br/api/v1/localidades/municipios'

res = requests.get(url)

#Obtendo o JSON da URL em formato texto (string) 
texto = res.text
print(type(texto))

<class 'str'>

Conversão de dados de string em formato JSON

In [ ]:
#O módulo json vem com um método chamado loads(), o s em loads() significa string. 
#Como queremos converter dados de string em JSON, usaremos este método.
obj = json.loads(texto)
print(type(obj))

<class 'list'>

In [ ]:
#Quantidade de municípios
print("Há {} municípios no total.".format(len(obj)))

Há 5570 municípios no total.

Vemos que o obj é do tipo <class 'list'> porque, neste caso, a resposta JSON, como visto, começa com colchetes [ ].

Vamos então normalizar os dados com o json_normalize(), de modo a 'abrir' os registros aninhados.

In [ ]:
import pandas as pd

#Normalizando os dados
df = pd.json_normalize(obj)
df.head()

,id,nome,microrregiao.id,microrregiao.nome,microrregiao.mesorregiao.id,microrregiao.mesorregiao.nome,microrregiao.mesorregiao.UF.id,microrregiao.mesorregiao.UF.sigla,microrregiao.mesorregiao.UF.nome,microrregiao.mesorregiao.UF.regiao.id,...,regiao-imediata.id,regiao-imediata.nome,regiao-imediata.regiao-intermediaria.id,regiao-imediata.regiao-intermediaria.nome,regiao-imediata.regiao-intermediaria.UF.id,regiao-imediata.regiao-intermediaria.UF.sigla,regiao-imediata.regiao-intermediaria.UF.nome,regiao-imediata.regiao-intermediaria.UF.regiao.id,regiao-imediata.regiao-intermediaria.UF.regiao.sigla,regiao-imediata.regiao-intermediaria.UF.regiao.nome
0,1100015,Alta Floresta D'Oeste,11006,Cacoal,1102,Leste Rondoniense,11,RO,Rondônia,1,...,110005,Cacoal,1102,Ji-Paraná,11,RO,Rondônia,1,N,Norte
1,1100023,Ariquemes,11003,Ariquemes,1102,Leste Rondoniense,11,RO,Rondônia,1,...,110002,Ariquemes,1101,Porto Velho,11,RO,Rondônia,1,N,Norte
2,1100031,Cabixi,11008,Colorado do Oeste,1102,Leste Rondoniense,11,RO,Rondônia,1,...,110006,Vilhena,1102,Ji-Paraná,11,RO,Rondônia,1,N,Norte
3,1100049,Cacoal,11006,Cacoal,1102,Leste Rondoniense,11,RO,Rondônia,1,...,110005,Cacoal,1102,Ji-Paraná,11,RO,Rondônia,1,N,Norte
4,1100056,Cerejeiras,11008,Colorado do Oeste,1102,Leste Rondoniense,11,RO,Rondônia,1,...,110006,Vilhena,1102,Ji-Paraná,11,RO,Rondônia,1,N,Norte

In [ ]:
df.shape

(5570, 22)

In [ ]:
df.columns

Index(['id', 'nome', 'microrregiao.id', 'microrregiao.nome',
       'microrregiao.mesorregiao.id', 'microrregiao.mesorregiao.nome',
       'microrregiao.mesorregiao.UF.id', 'microrregiao.mesorregiao.UF.sigla',
       'microrregiao.mesorregiao.UF.nome',
       'microrregiao.mesorregiao.UF.regiao.id',
       'microrregiao.mesorregiao.UF.regiao.sigla',
       'microrregiao.mesorregiao.UF.regiao.nome', 'regiao-imediata.id',
       'regiao-imediata.nome', 'regiao-imediata.regiao-intermediaria.id',
       'regiao-imediata.regiao-intermediaria.nome',
       'regiao-imediata.regiao-intermediaria.UF.id',
       'regiao-imediata.regiao-intermediaria.UF.sigla',
       'regiao-imediata.regiao-intermediaria.UF.nome',
       'regiao-imediata.regiao-intermediaria.UF.regiao.id',
       'regiao-imediata.regiao-intermediaria.UF.regiao.sigla',
       'regiao-imediata.regiao-intermediaria.UF.regiao.nome'],
      dtype='object')

In [ ]:
#Selecionando os campos
municipios_ibge = df[['id', 'nome', 'microrregiao.mesorregiao.UF.nome', 'microrregiao.mesorregiao.UF.sigla', 'regiao-imediata.regiao-intermediaria.UF.regiao.nome', 'regiao-imediata.regiao-intermediaria.UF.regiao.sigla']]
municipios_ibge.head()

,id,nome,microrregiao.mesorregiao.UF.nome,microrregiao.mesorregiao.UF.sigla,regiao-imediata.regiao-intermediaria.UF.regiao.nome,regiao-imediata.regiao-intermediaria.UF.regiao.sigla
0,1100015,Alta Floresta D'Oeste,Rondônia,RO,Norte,N
1,1100023,Ariquemes,Rondônia,RO,Norte,N
2,1100031,Cabixi,Rondônia,RO,Norte,N
3,1100049,Cacoal,Rondônia,RO,Norte,N
4,1100056,Cerejeiras,Rondônia,RO,Norte,N

In [ ]:
#Renomeando as colunas

renomear = {
    'nome': 'Municipio',
    'microrregiao.mesorregiao.UF.nome': 'Estado',
    'microrregiao.mesorregiao.UF.sigla': 'UF',
    'regiao-imediata.regiao-intermediaria.UF.regiao.nome': 'Regiao',
    'regiao-imediata.regiao-intermediaria.UF.regiao.sigla': 'Regiao_Sigla'
}

municipios_ibge = municipios_ibge.rename(columns = renomear)
municipios_ibge.head()

        id              Municipio    Estado  UF Regiao Regiao_Sigla
0  1100015  Alta Floresta D'Oeste  Rondônia  RO  Norte            N
1  1100023              Ariquemes  Rondônia  RO  Norte            N
2  1100031                 Cabixi  Rondônia  RO  Norte            N
3  1100049                 Cacoal  Rondônia  RO  Norte            N
4  1100056             Cerejeiras  Rondônia  RO  Norte            N

In [ ]:
#Exportando csv

municipios_ibge.to_csv('municipios_ibge.csv', index=False, encoding='utf-8')